services:
  backend:
    build: ./backend
    container_name: smartdoc-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: smartdoc-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
